
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8001"
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    depends_on:
      - auth-service

volumes:
  mongo-data:
