
services:
  auth-service:
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
